/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;

/**
 *
 * @author leonin04
 */
public class VisualUI extends javax.swing.JFrame implements UI {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VisualUI.class.getName());

    private Cursors flechas;
    /**
     * Creates new form VisualUI
     */
    public VisualUI() {
        initComponents();
        setVisible(true);
        flechas = new Cursors(this, true);
    }
    
    @Override
    public Directions nextMove(){
        Directions direction = flechas.getDirection();
        return direction;
    }
    
    @Override
    public void showGame(GameState gameState){
        laberinto.setText(gameState.getLabyrinth());
        datosJugadores.setText(gameState.getPlayers());
        datosMonstruos.setText(gameState.getMonsters());
        log.setText(gameState.getLog());
        if (gameState.getWinner()){
            ganador.setText(("Felicidades Player " + gameState.getCurrentPlayer() + " ,¡has ganado!"));
        } else {
            ganador.setText(("No hay ganador"));
        }
        currentPlayer.setText("Current Player: " + gameState.getCurrentPlayer());
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPanel1 = new javax.swing.JScrollPane();
        laberinto = new javax.swing.JTextArea();
        JScrollPanel2 = new javax.swing.JScrollPane();
        datosJugadores = new javax.swing.JTextArea();
        JScrollPanel3 = new javax.swing.JScrollPane();
        datosMonstruos = new javax.swing.JTextArea();
        jScrollPanel4 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        ganador = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentPlayer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 215, 95));
        setForeground(java.awt.Color.white);
        setResizable(false);

        laberinto.setColumns(20);
        laberinto.setFont(new java.awt.Font("Courier", 0, 18)); // NOI18N
        laberinto.setLineWrap(true);
        laberinto.setRows(5);
        laberinto.setWrapStyleWord(true);
        JScrollPanel1.setViewportView(laberinto);

        datosJugadores.setColumns(20);
        datosJugadores.setLineWrap(true);
        datosJugadores.setRows(5);
        datosJugadores.setWrapStyleWord(true);
        JScrollPanel2.setViewportView(datosJugadores);

        datosMonstruos.setColumns(20);
        datosMonstruos.setLineWrap(true);
        datosMonstruos.setRows(5);
        datosMonstruos.setWrapStyleWord(true);
        JScrollPanel3.setViewportView(datosMonstruos);

        log.setColumns(20);
        log.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        log.setLineWrap(true);
        log.setRows(5);
        log.setWrapStyleWord(true);
        jScrollPanel4.setViewportView(log);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        ganador.setColumns(20);
        ganador.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        ganador.setLineWrap(true);
        ganador.setRows(5);
        ganador.setWrapStyleWord(true);
        ganador.setAutoscrolls(false);
        jScrollPane1.setViewportView(ganador);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        currentPlayer.setColumns(20);
        currentPlayer.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        currentPlayer.setRows(5);
        currentPlayer.setPreferredSize(new java.awt.Dimension(256, 56));
        jScrollPane2.setViewportView(currentPlayer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JScrollPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JScrollPanel2)
                            .addComponent(JScrollPanel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JScrollPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JScrollPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(JScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPanel1;
    private javax.swing.JScrollPane JScrollPanel2;
    private javax.swing.JScrollPane JScrollPanel3;
    private javax.swing.JTextArea currentPlayer;
    private javax.swing.JTextArea datosJugadores;
    private javax.swing.JTextArea datosMonstruos;
    private javax.swing.JTextArea ganador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPanel4;
    private javax.swing.JTextArea laberinto;
    private javax.swing.JTextArea log;
    // End of variables declaration//GEN-END:variables
}
